### ISSUE TITLE
The extension probably doesn't really need 'Pro' edition

### ISSUE THREAD

**Issue by JohnLudlow** [mikefourie/MyHistory#4]
The extension has this in its manifest:
 ` <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="12.0" /> `

(from the 2013 version)

One of our tech authors doesn't have an MSDN license so she can only install the integrated shell (in its Team Explorer guise), or Community.

'Pro' is, I think, simply the default and either of the other two lower editions would be sufficient. (The one caveat, of course, is that integrated shell also covers SQL Server Management Studio et al, so maybe Community is better).

**Comment by mikefourie** [comment]
thanks, updated for 2015

**Comment by JohnLudlow** [comment]
Thanks Mike. I'll let the team know.
